export const Const = {
  maxWidth: 1000,
  topNav: 64,
  drawerWidth: 275,
  reactScrollProps: {
    spy: true,
    smooth: true,
    duration: 400,
    activeClass: 'scroll-active',
    offset: -80,
  },
  rad: 10,
  pad: 20,
  css: {
    navbg: 'var(--nav-bg)',
    bgc0: 'var(--bgc-0)',
    bgc1: 'var(--bgc-1)',
    bgc2: 'var(--bgc-2)',
    fc0: 'var(--fc-0)',
    fc1: 'var(--fc-1)',
    pallet0: 'var(--pallet-0)',
    pallet1: 'var(--pallet-1)',
    shadow: 'var(--shadow)',
    border: 'var(--border)',
    sm: 'var(--fs-sm)',
    md: 'var(--fs-md)',
    lg: 'var(--fs-lg)',
    xlg: 'var(--fs-xl)',
    xxlg: 'var(--fs-xxl)',
    xxxlg: 'var(--fs-xxxl)',
    contentPad: 'var(--content-pad)',
    cardRad: 'var(--card-rad)',
    nameSize: 'var(--name-size)',
    cardGrid: 'var(--card-grid)',
    aboutGrid: 'var(--about-grid)',
    hoverBg: 'var(--hovbg)',
  },
}
